resource_group_name = "my-function-rg"
location = "East US"
storage_account_name = "mystorageacct123"
app_service_plan_name = "my-function-plan"
function_app_name = "myfunctionapp"
runtime_stack = "dotnet"
functions_worker_runtime = "dotnet"

acr_name           = "devacr123"
acr_sku            = "Basic"
container_app_env_name = "dev-container-app-env"